### ISSUE TITLE
Error when trying to open Settings activity 

### ISSUE THREAD

**Issue by takieddine01** [christoffer/readtracker#19]
I get this error when i try to open Settings activity 
**android.view.InflateException: Binary XML file line #19: Error inflating class android.widget.CheckBox**

 main
                                                                     android.view.InflateException: Binary XML file line #19: Error inflating class android.widget.CheckBox
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                         at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                         at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                         at android.preference.Preference.onCreateView(Preference.java:487)
                                                                         at android.preference.Preference.getView(Preference.java:458)
                                                                         at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:221)
                                                                         at android.widget.AbsListView.obtainView(AbsListView.java:2177)
                                                                         at android.widget.ListView.makeAndAddView(ListView.java:1840)
                                                                         at android.widget.ListView.fillDown(ListView.java:675)
                                                                         at android.widget.ListView.fillFromTop(ListView.java:736)
                                                                         at android.widget.ListView.layoutChildren(ListView.java:1655)
                                                                         at android.widget.AbsListView.onLayout(AbsListView.java:2012)
                                                                         at android.view.View.layout(View.java:14289)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4562)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                         at android.view.View.layout(View.java:14289)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4562)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                         at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1660)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1436)
                                                                         at android.view.View.layout(View.java:14289)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4562)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                         at android.view.View.layout(View.java:14289)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4562)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                         at android.view.View.layout(View.java:14289)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4562)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                         at android.view.View.layout(View.java:14289)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4562)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                         at android.view.View.layout(View.java:14289)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4562)
                                                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1976)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1730)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:562)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:532)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
                                                                         at android.os.Handler.handleCallback(Handler.java:730)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                         at android.os.Looper.loop(Looper.java:137)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:525)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: java.lang.reflect.InvocationTargetException
                                                                     	at java.lang.reflect.Construc

**Comment by takieddine01** [comment]
I fix the problem in my local copy by downgrading the version number of the libraries : appcompact and support like this :
from
compile 'com.android.support:appcompat-v7:23.2.0
compile 'com.android.support:support-v4:23.2.0
to 
compile 'com.android.support:appcompat-v7:23.1.1
compile 'com.android.support:support-v4:23.1.1

in the gradle file

**Comment by christoffer** [comment]
Thanks for reporting this!

I was able to reproduce this and it seems to go away with a higher version of the SDK as well. Will mark this as resolved with b51258d05d0589a8b2811a84cefd53f006b1ec4a.

Let me know if you still see this!
